#!/bin/sh
bspc config normal_border_color   '#2F343F'
bspc config active_border_color   '#8E9EC2'
bspc config focused_border_color  '#4084D6'
bspc config presel_feedback_color '#4084D6'

bspc config split_ratio        0.5
bspc config borderless_monocle true
bspc config gapless_monocle    false
bspc config window_gap         5
bspc config click_to_focus     true

bspc config top_padding        -5
bspc config bottom_padding     -5
bspc config left_padding       -5
bspc config right_padding      -5

for m in $(bspc query -M); do
	bspc monitor $m -d 1 2 3 4
done
