#!/bin/sh

# # Configuration
bspc config split_ratio                0.5
bspc config window_gap                 5
bspc config borderless_monocle         false
bspc config gapless_monocle            true
bspc config pointer_follows_monitor    false
bspc config auto_alternate             false
bspc config auto_cancel                false
bspc config history_aware_focus        true
bspc config normal_border_color        '#2f343f'
bspc config active_border_color        '#8E9EC2'
bspc config focused_border_color       '#4084D6'
bspc config presel_feedback_color      '#4084D6'
bspc config urgent_border_color        '#c74528'
bspc config click_to_focus             true

# Monitor setup
for m in $(bspc query -M); do
	bspc desktop $(bspc query -m $m -D) -n "$m-1"

	for d in $(seq 2 4); do
		bspc monitor $m -a "$m-$d"
	done
done

for d in $(bspc query -D); do
	bspc config -d $d border_width 2
done
